name: CI

on:
  push:
  pull_request:

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g office-addin-manifest
      - run: office-addin-manifest info manifest.xml
      - run: office-addin-manifest validate manifest.xml
